// src/components/ui/StatsModal.jsx
import React from 'react';
import { X, TrendingUp } from 'lucide-react';
import { ListSkeleton } from './ContentSkeletons';

const formatDate = (value) => {
  if (!value) return 'Unknown date';

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'Unknown date';

  return date.toLocaleString('en-US', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

const typeStyles = {
  message: 'bg-orange-50 border-orange-200 text-orange-900',
  comment: 'bg-amber-50 border-amber-200 text-amber-900',
  like: 'bg-blue-50 border-blue-200 text-blue-900',
  dislike: 'bg-rose-50 border-rose-200 text-rose-900',
  game: 'bg-violet-50 border-violet-200 text-violet-900',
  canvas: 'bg-emerald-50 border-emerald-200 text-emerald-900',
  read_messages: 'bg-slate-50 border-slate-200 text-slate-900',
  useful: 'bg-yellow-50 border-yellow-200 text-yellow-900'
};

const typeLabel = {
  message: 'Message',
  comment: 'Comment',
  like: 'Like',
  dislike: 'Dislike',
  game: 'Mini-game',
  canvas: 'Canvas',
  read_messages: 'Reading',
  useful: 'Useful'
};

const StatsModal = ({ stats, onClose }) => {
  if (!stats) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
        <div className="bg-white rounded-2xl p-6 max-w-md w-full mx-4 shadow-2xl">
          <ListSkeleton label="Loading spending history" count={3} />
        </div>
      </div>
    );
  }

  const history = Array.isArray(stats.history) ? stats.history : [];

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl p-6 max-w-3xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-start gap-4 mb-4">
          <div>
            <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
              <TrendingUp className="w-6 h-6 text-orange-500" />
              Spending history
            </h2>
            <p className="text-sm text-gray-500 mt-1">
              Recent shell expenses generated by your actions on the network.
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition"
            aria-label="Close"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-gray-600">
          {history.length} events tracked
        </div>

        {history.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-gray-200 bg-gray-50 p-10 text-center">
            <p className="text-gray-700 font-semibold">No shell expenses yet.</p>
            <p className="text-sm text-gray-500 mt-2">
              Your posts, reactions, game sessions, canvas actions, and feed reads will appear here.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {history.map((event) => {
              const eventType = event.type || 'message';
              const styles = typeStyles[eventType] || typeStyles.message;
              const label = typeLabel[eventType] || 'Action';
              const amount = Number(event.amount || 0);

              return (
                <div
                  key={event.id}
                  className={`rounded-2xl border p-4 ${styles}`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
                    <div className="min-w-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="inline-flex items-center rounded-full bg-white/70 px-2.5 py-1 text-xs font-bold uppercase tracking-wide">
                          {label}
                        </span>
                        <span className="text-xs text-current/70">
                          {formatDate(event.created_at)}
                        </span>
                      </div>
                      <p className="mt-2 font-semibold text-base">
                        {event.title}
                      </p>
                      <p className="mt-1 text-sm text-current/80 break-words">
                        {event.description}
                      </p>
                      {event.detail && (
                        <p className="mt-2 text-xs text-current/70">
                          {event.detail}
                        </p>
                      )}
                    </div>

                    <div className="sm:text-right shrink-0">
                      <p className="text-lg font-black">
                        -{Math.abs(amount).toFixed(8)} shells
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        <button
          onClick={onClose}
          className="w-full mt-6 bg-gray-900 text-white px-6 py-3 rounded-xl font-semibold hover:bg-gray-800 transition"
        >
          Close
        </button>
      </div>
    </div>
  );
};

export default StatsModal;
